[Server]
project = "k8s-server"
listenAddr = ":9090"

[Kubenertes]
config = "conf/mac_config.conf"
podlogtailline = 2000

[Log]
logdir = "logs"
logfile = "k8s-server.log"
level = "debug"
pattern = "development"
maxsize = 1
maxbackups = 3
maxage = 7
compress = true

[User]
adminuser = "admin"
adminpwd = "123456"

[DB]
DbType = "mysql"
DbHost = "host.docker.internal"
DbPort = 3306
DbName = "k8s_demo"
DbUser = "luis"
DbPwd = "qwe123"
LogMode = false
MaxIdleConns = 10
MaxOpenConns = 100
MaxLifeTime = 30